/**
 ******************************************************************************
 * @file      startup_stm32h7s3l8hx.s
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32H7S3L8Hx device vector table for GCC toolchain.
 *            This module performs:
 *                - Set the initial SP
 *                - Set the initial PC == Reset_Handler,
 *                - Set the vector table entries with the exceptions ISR address
 *                - Branches to main in the C library (which eventually
 *                  calls main()).
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

.syntax unified
.cpu cortex-m7
.fpu softvfp
.thumb

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss

/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0          /* set stack pointer */
/* Call the clock system initialization function.*/
  bl  SystemInit

/* Copy the data segment initializers from flash to SRAM */
  ldr r0, =_sdata
  ldr r1, =_edata
  ldr r2, =_sidata
  movs r3, #0
  b LoopCopyDataInit

CopyDataInit:
  ldr r4, [r2, r3]
  str r4, [r0, r3]
  adds r3, r3, #4

LoopCopyDataInit:
  adds r4, r0, r3
  cmp r4, r1
  bcc CopyDataInit

/* Zero fill the bss segment. */
  ldr r2, =_sbss
  ldr r4, =_ebss
  movs r3, #0
  b LoopFillZerobss

FillZerobss:
  str  r3, [r2]
  adds r2, r2, #4

LoopFillZerobss:
  cmp r2, r4
  bcc FillZerobss


/* Call static constructors */
  bl __libc_init_array
/* Call the application's entry point.*/

  bl main

LoopForever:
  b LoopForever

  .size Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler

/******************************************************************************
*
* The STM32H7S3L8Hx vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/


  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object

g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word NMI_Handler
  .word HardFault_Handler
  .word	MemManage_Handler
  .word	BusFault_Handler
  .word	UsageFault_Handler
  .word	0
  .word	0
  .word	0
  .word	0
  .word	SVC_Handler
  .word	DebugMon_Handler
  .word	0
  .word	PendSV_Handler
  .word	SysTick_Handler
  .word	PVD_AVD_IRQHandler     			/* PVD and AVD through the EXTI line                         */
  .word	0                      			/* Reserved                                                  */
  .word	DTS_IRQHandler         			/* DTS global interrupt                                      */
  .word	IWDG_IRQHandler        			/* Independent watchdog interrupt                            */
  .word	WWDG_IRQHandler        			/* Window Watchdog interrupt                                 */
  .word	RCC_IRQHandler         			/* RCC global interrupt                                      */
  .word	LOOKUP_IRQHandler      			/* LOOKUP/Overstack                                          */
  .word	CACHE_ECC_IRQHandler   			/* Error ECC cache                                           */
  .word	FLASH_IRQHandler       			/* Flash memory                                              */
  .word	ECC_FPU_IRQHandler     			/* ECC/FPU/ All flag from exec                               */
  .word	FPU_IRQHandler         			/* FPU safety Flag                                           */
  .word	0                      			/* Reserved                                                  */
  .word	0                      			/* Reserved                                                  */
  .word	TAMP_IRQHandler        			/* RTC tamper and timestamp interrupts through the EXTI line */
  .word	0                      			/* Reserved                                                  */
  .word	0                      			/* Reserved                                                  */
  .word	EXTI0_IRQHandler       			/* EXTI Line 0 interrupt through the EXTI line               */
  .word	EXTI1_IRQHandler       			/* EXTI Line 1 interrupt through the EXTI line               */
  .word	EXTI2_IRQHandler       			/* EXTI Line 2 interrupt through the EXTI line               */
  .word	EXTI3_IRQHandler       			/* EXTI Line 3 interrupt through the EXTI line               */
  .word	EXTI4_IRQHandler       			/* EXTI Line 4 interrupt through the EXTI line               */
  .word	EXTI5_IRQHandler       			/* EXTI Line 5 interrupt through the EXTI line               */
  .word	EXTI6_IRQHandler       			/* EXTI Line 6 interrupt through the EXTI line               */
  .word	EXTI7_IRQHandler       			/* EXTI Line 7 interrupt through the EXTI line               */
  .word	EXTI8_IRQHandler       			/* EXTI Line 8 interrupt through the EXTI line               */
  .word	EXTI9_IRQHandler       			/* EXTI Line 9 interrupt through the EXTI line               */
  .word	EXTI10_IRQHandler      			/* EXTI Line 10 interrupt through the EXTI line              */
  .word	EXTI11_IRQHandler      			/* EXTI Line 11 interrupt through the EXTI line              */
  .word	EXTI12_IRQHandler      			/* EXTI Line 12 interrupt through the EXTI line              */
  .word	EXTI13_IRQHandler      			/* EXTI Line 13 interrupt through the EXTI line              */
  .word	EXTI14_IRQHandler      			/* EXTI Line 14 interrupt through the EXTI line              */
  .word	EXTI15_IRQHandler      			/* EXTI Line 15 interrupt through the EXTI line              */
  .word	RTC_IRQHandler         			/* RTC Wakeup and Alarm interrupt through the EXTI line      */
  .word	SAES_IRQHandler        			/* SAES global interrupt                                     */
  .word	AES_IRQHandler         			/* AES global interrupt                                      */
  .word	PKA_IRQHandler         			/* PKA global interrupt                                      */
  .word	HASH_IRQHandler        			/* HASH global interrupt                                     */
  .word	RNG_IRQHandler         			/* RNG global interrupt                                      */
  .word	ADC1_2_IRQHandler      			/* ADC1/2 global interrupt                                   */
  .word	GPDMA1_CH0_IRQHandler  			/* GPDMA1 channel 0 interrupt                                */
  .word	GPDMA1_CH1_IRQHandler  			/* GPDMA1 channel 1 interrupt                                */
  .word	GPDMA1_CH2_IRQHandler  			/* GPDMA1 channel 2 interrupt                                */
  .word	GPDMA1_CH3_IRQHandler  			/* GPDMA1 channel 3 interrupt                                */
  .word	GPDMA1_CH4_IRQHandler  			/* GPDMA1 channel 4 interrupt                                */
  .word	GPDMA1_CH5_IRQHandler  			/* GPDMA1 channel 5 interrupt                                */
  .word	GPDMA1_CH6_IRQHandler  			/* GPDMA1 channel 6 interrupt                                */
  .word	GPDMA1_CH7_IRQHandler  			/* GPDMA1 channel 7 interrupt                                */
  .word	TIM1_BRK_IRQHandler    			/* TIM1 Break interrupt                                      */
  .word	TIM1_UP_IRQHandler     			/* TIM1 Update interrupt (tim_upd_it)                        */
  .word	TIM1_TRG_COM_IRQHandler			/* TIM1 Trigger and Commutation interrupts                   */
  .word	TIM1_CC_IRQHandler     			/* TIM1 Capture Compare interrupt                            */
  .word	TIM2_IRQHandler        			/* TIM2 global interrupt                                     */
  .word	TIM3_IRQHandler        			/* TIM3 global interrupt                                     */
  .word	TIM4_IRQHandler        			/* TIM4 global interrupt                                     */
  .word	TIM5_IRQHandler        			/* TIM5 global interrupt                                     */
  .word	TIM6_IRQHandler        			/* TIM6 global interrupt                                     */
  .word	TIM7_IRQHandler        			/* TIM7 global interrupt                                     */
  .word	TIM9_IRQHandler        			/* TIM9 global interrupt                                     */
  .word	SPI1_IRQHandler        			/* SPI1 global interrupt                                     */
  .word	SPI2_IRQHandler        			/* SPI2 global interrupt                                     */
  .word	SPI3_IRQHandler        			/* SPI3 global interrupt                                     */
  .word	SPI4_IRQHandler        			/* SPI4 global interrupt                                     */
  .word	SPI5_IRQHandler        			/* SPI5 global interrupt                                     */
  .word	SPI6_IRQHandler        			/* SPI6 global interrupt                                     */
  .word	HPDMA1_CH0_IRQHandler  			/* HPDMA1 channel 0 interrupt                                */
  .word	HPDMA1_CH1_IRQHandler  			/* HPDMA1 channel 1 interrupt                                */
  .word	HPDMA1_CH2_IRQHandler  			/* HPDMA1 channel 2 interrupt                                */
  .word	HPDMA1_CH3_IRQHandler  			/* HPDMA1 channel 3 interrupt                                */
  .word	HPDMA1_CH4_IRQHandler  			/* HPDMA1 channel 4 interrupt                                */
  .word	HPDMA1_CH5_IRQHandler  			/* HPDMA1 channel 5 interrupt                                */
  .word	HPDMA1_CH6_IRQHandler  			/* HPDMA1 channel 6 interrupt                                */
  .word	HPDMA1_CH7_IRQHandler  			/* HPDMA1 channel 7 interrupt                                */
  .word	SAI1_A_IRQHandler      			/* SAI1 global interrupt A                                   */
  .word	SAI1_B_IRQHandler      			/* SAI1 global interrupt B                                   */
  .word	SAI2_A_IRQHandler      			/* SAI2 global interrupt A                                   */
  .word	SAI2_B_IRQHandler      			/* SAI2 global interrupt B                                   */
  .word	I2C1_EV_IRQHandler     			/* I2C1 event interrupt                                      */
  .word	I2C1_ER_IRQHandler     			/* I2C1 error interrupt                                      */
  .word	I2C2_EV_IRQHandler     			/* I2C2 event interrupt                                      */
  .word	I2C2_ER_IRQHandler     			/* I2C2 error interrupt                                      */
  .word	I2C3_EV_IRQHandler     			/* I2C3 event interrupt                                      */
  .word	I2C3_ER_IRQHandler     			/* I2C3 error interrupt                                      */
  .word	USART1_IRQHandler      			/* USART1 global interrupt                                   */
  .word	USART2_IRQHandler      			/* USART2 global interrupt                                   */
  .word	USART3_IRQHandler      			/* USART3 global interrupt                                   */
  .word	UART4_IRQHandler       			/* UART4 global interrupt                                    */
  .word	UART5_IRQHandler       			/* UART5 global interrupt                                    */
  .word	UART7_IRQHandler       			/* UART7 global interrupt                                    */
  .word	UART8_IRQHandler       			/* UART8 global interrupt                                    */
  .word	I3C1_EV_IRQHandler     			/* I3C1 event interrupt                                      */
  .word	I3C1_ER_IRQHandler     			/* I3C1 error interrupt                                      */
  .word	OTG_HS_IRQHandler      			/* USB OTG HS global interrupt                               */
  .word	ETH_IRQHandler         			/* Ethernet global interrupt                                 */
  .word	CORDIC_IRQHandler      			/* CORDIC interrupt                                          */
  .word	GFXTIM_IRQHandler      			/* GFXTIM global interrupt                                   */
  .word	DCMIPP_IRQHandler      			/* DCMIPP global interrupt                                   */
  .word	LTDC_IRQHandler        			/* LCD global interrupt                                      */
  .word	LTDC_ER_IRQHandler     			/* LCD error interrupt                                       */
  .word	DMA2D_IRQHandler       			/* DMA2D global interrupt                                    */
  .word	JPEG_IRQHandler        			/* JPEG global interrupt                                     */
  .word	GFXMMU_IRQHandler      			/* GFXMMU global interrupt                                   */
  .word	I3C1_WKUP_IRQHandler   			/* I3C wakeup Interrupt through EXTI line                    */
  .word	MCE1_IRQHandler        			/* MCE1 global interrupt                                     */
  .word	MCE2_IRQHandler        			/* MCE2 global interrupt                                     */
  .word	MCE3_IRQHandler        			/* MCE3 global interrupt                                     */
  .word	OSPI1_IRQHandler       			/* OSPI1 / HSPI1 global interrupt                            */
  .word	OSPI2_IRQHandler       			/* OSPI2 global interrupt                                    */
  .word	FMC_IRQHandler         			/* FMC global interrupt                                      */
  .word	SDMMC1_IRQHandler      			/* SDMMC1 global interrupt                                   */
  .word	SDMMC2_IRQHandler      			/* SDMMC2 global interrupt                                   */
  .word	0                      			/* Reserved                                                  */
  .word	0                      			/* Reserved                                                  */
  .word	OTG_FS_IRQHandler      			/* USB OTG FS global interrupt                               */
  .word	TIM12_IRQHandler       			/* TIM12 global interrupt                                    */
  .word	TIM13_IRQHandler       			/* TIM13 global interrupt                                    */
  .word	TIM14_IRQHandler       			/* TIM14 global interrupt                                    */
  .word	TIM15_IRQHandler       			/* TIM15 global interrupt                                    */
  .word	TIM16_IRQHandler       			/* TIM16 global interrupt                                    */
  .word	TIM17_IRQHandler       			/* TIM17 global interrupt                                    */
  .word	LPTIM1_IRQHandler      			/* LPTIM1 global interrupt                                   */
  .word	LPTIM2_IRQHandler      			/* LPTIM2 global interrupt                                   */
  .word	LPTIM3_IRQHandler      			/* LPTIM3 global interrupt                                   */
  .word	LPTIM4_IRQHandler      			/* LPTIM4 global interrupt                                   */
  .word	LPTIM5_IRQHandler      			/* LPTIM5 global interrupt                                   */
  .word	SPDIF_RX_IRQHandler    			/* SPDIFRX global interrupt                                  */
  .word	MDIOS_IRQHandler       			/* MDIOS global interrupt                                    */
  .word	ADF1_FLT0_IRQHandler   			/* ADF1 filter 0 global interrupt                            */
  .word	CRS_IRQHandler         			/* CRS global interrupt                                      */
  .word	UCPD1_IRQHandler       			/* UCPD global interrupt                                     */
  .word	CEC_IRQHandler         			/* CEC global interrupt                                      */
  .word	PSSI_IRQHandler        			/* PSSI global interrupt                                     */
  .word	LPUART1_IRQHandler     			/* LPUART1 LPUART1 global interrupt                          */
  .word	WAKEUP_PIN_IRQHandler  			/* Interrupt for 4 wakeup pins (1, 2, 3, 4)through EXTI line */
  .word	GPDMA1_CH8_IRQHandler  			/* GPDMA1 channel 8 interrupt                                */
  .word	GPDMA1_CH9_IRQHandler  			/* GPDMA1 channel 9 interrupt                                */
  .word	GPDMA1_CH10_IRQHandler 			/* GPDMA1 channel 10 interrupt                               */
  .word	GPDMA1_CH11_IRQHandler 			/* GPDMA1 channel 11 interrupt                               */
  .word	GPDMA1_CH12_IRQHandler 			/* GPDMA1 channel 12 interrupt                               */
  .word	GPDMA1_CH13_IRQHandler 			/* GPDMA1 channel 13 interrupt                               */
  .word	GPDMA1_CH14_IRQHandler 			/* GPDMA1 channel 14 interrupt                               */
  .word	GPDMA1_CH15_IRQHandler 			/* GPDMA1 channel 15 interrupt                               */
  .word	HPDMA1_CH8_IRQHandler  			/* HPDMA1 channel 8 interrupt                                */
  .word	HPDMA1_CH9_IRQHandler  			/* HPDMA1 channel 9 interrupt                                */
  .word	HPDMA1_CH10_IRQHandler 			/* HPDMA1 channel 10 interrupt                               */
  .word	HPDMA1_CH11_IRQHandler 			/* HPDMA1 channel 11 interrupt                               */
  .word	HPDMA1_CH12_IRQHandler 			/* HPDMA1 channel 12 interrupt                               */
  .word	HPDMA1_CH13_IRQHandler 			/* HPDMA1 channel 13 interrupt                               */
  .word	HPDMA1_CH14_IRQHandler 			/* HPDMA1 channel 14 interrupt                               */
  .word	HPDMA1_CH15_IRQHandler 			/* HPDMA1 channel 15 interrupt                               */
  .word	GPU2D_IRQHandler       			/* GPU2D global interrupt                                    */
  .word	GPU2D_ER_IRQHandler    			/* GPU2D error interrupt                                     */
  .word	TCACHE_IRQHandler      			/* GPU cache interrupt                                       */
  .word	FDCAN1_IT0_IRQHandler  			/* FDCAN1 Interrupt 0                                        */
  .word	FDCAN1_IT1_IRQHandler  			/* FDCAN1 Interrupt 1                                        */
  .word	FDCAN2_IT0_IRQHandler  			/* FDCAN2 Interrupt 0                                        */
  .word	FDCAN2_IT1_IRQHandler  			/* FDCAN2 Interrupt 1                                        */
  .size g_pfnVectors, .-g_pfnVectors

/*******************************************************************************
*
* Provide weak aliases for each Exception handler to the Default_Handler.
* As they are weak aliases, any function with the same name will override
* this definition.
*
*******************************************************************************/

	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

	.weak	MemManage_Handler
	.thumb_set MemManage_Handler,Default_Handler

	.weak	BusFault_Handler
	.thumb_set BusFault_Handler,Default_Handler

	.weak	UsageFault_Handler
	.thumb_set UsageFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	DebugMon_Handler
	.thumb_set DebugMon_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	.weak	PVD_AVD_IRQHandler
	.thumb_set PVD_AVD_IRQHandler,Default_Handler

	.weak	DTS_IRQHandler
	.thumb_set DTS_IRQHandler,Default_Handler

	.weak	IWDG_IRQHandler
	.thumb_set IWDG_IRQHandler,Default_Handler

	.weak	WWDG_IRQHandler
	.thumb_set WWDG_IRQHandler,Default_Handler

	.weak	RCC_IRQHandler
	.thumb_set RCC_IRQHandler,Default_Handler

	.weak	LOOKUP_IRQHandler
	.thumb_set LOOKUP_IRQHandler,Default_Handler

	.weak	CACHE_ECC_IRQHandler
	.thumb_set CACHE_ECC_IRQHandler,Default_Handler

	.weak	FLASH_IRQHandler
	.thumb_set FLASH_IRQHandler,Default_Handler

	.weak	ECC_FPU_IRQHandler
	.thumb_set ECC_FPU_IRQHandler,Default_Handler

	.weak	FPU_IRQHandler
	.thumb_set FPU_IRQHandler,Default_Handler

	.weak	TAMP_IRQHandler
	.thumb_set TAMP_IRQHandler,Default_Handler

	.weak	EXTI0_IRQHandler
	.thumb_set EXTI0_IRQHandler,Default_Handler

	.weak	EXTI1_IRQHandler
	.thumb_set EXTI1_IRQHandler,Default_Handler

	.weak	EXTI2_IRQHandler
	.thumb_set EXTI2_IRQHandler,Default_Handler

	.weak	EXTI3_IRQHandler
	.thumb_set EXTI3_IRQHandler,Default_Handler

	.weak	EXTI4_IRQHandler
	.thumb_set EXTI4_IRQHandler,Default_Handler

	.weak	EXTI5_IRQHandler
	.thumb_set EXTI5_IRQHandler,Default_Handler

	.weak	EXTI6_IRQHandler
	.thumb_set EXTI6_IRQHandler,Default_Handler

	.weak	EXTI7_IRQHandler
	.thumb_set EXTI7_IRQHandler,Default_Handler

	.weak	EXTI8_IRQHandler
	.thumb_set EXTI8_IRQHandler,Default_Handler

	.weak	EXTI9_IRQHandler
	.thumb_set EXTI9_IRQHandler,Default_Handler

	.weak	EXTI10_IRQHandler
	.thumb_set EXTI10_IRQHandler,Default_Handler

	.weak	EXTI11_IRQHandler
	.thumb_set EXTI11_IRQHandler,Default_Handler

	.weak	EXTI12_IRQHandler
	.thumb_set EXTI12_IRQHandler,Default_Handler

	.weak	EXTI13_IRQHandler
	.thumb_set EXTI13_IRQHandler,Default_Handler

	.weak	EXTI14_IRQHandler
	.thumb_set EXTI14_IRQHandler,Default_Handler

	.weak	EXTI15_IRQHandler
	.thumb_set EXTI15_IRQHandler,Default_Handler

	.weak	RTC_IRQHandler
	.thumb_set RTC_IRQHandler,Default_Handler

	.weak	SAES_IRQHandler
	.thumb_set SAES_IRQHandler,Default_Handler

	.weak	AES_IRQHandler
	.thumb_set AES_IRQHandler,Default_Handler

	.weak	PKA_IRQHandler
	.thumb_set PKA_IRQHandler,Default_Handler

	.weak	HASH_IRQHandler
	.thumb_set HASH_IRQHandler,Default_Handler

	.weak	RNG_IRQHandler
	.thumb_set RNG_IRQHandler,Default_Handler

	.weak	ADC1_2_IRQHandler
	.thumb_set ADC1_2_IRQHandler,Default_Handler

	.weak	GPDMA1_CH0_IRQHandler
	.thumb_set GPDMA1_CH0_IRQHandler,Default_Handler

	.weak	GPDMA1_CH1_IRQHandler
	.thumb_set GPDMA1_CH1_IRQHandler,Default_Handler

	.weak	GPDMA1_CH2_IRQHandler
	.thumb_set GPDMA1_CH2_IRQHandler,Default_Handler

	.weak	GPDMA1_CH3_IRQHandler
	.thumb_set GPDMA1_CH3_IRQHandler,Default_Handler

	.weak	GPDMA1_CH4_IRQHandler
	.thumb_set GPDMA1_CH4_IRQHandler,Default_Handler

	.weak	GPDMA1_CH5_IRQHandler
	.thumb_set GPDMA1_CH5_IRQHandler,Default_Handler

	.weak	GPDMA1_CH6_IRQHandler
	.thumb_set GPDMA1_CH6_IRQHandler,Default_Handler

	.weak	GPDMA1_CH7_IRQHandler
	.thumb_set GPDMA1_CH7_IRQHandler,Default_Handler

	.weak	TIM1_BRK_IRQHandler
	.thumb_set TIM1_BRK_IRQHandler,Default_Handler

	.weak	TIM1_UP_IRQHandler
	.thumb_set TIM1_UP_IRQHandler,Default_Handler

	.weak	TIM1_TRG_COM_IRQHandler
	.thumb_set TIM1_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM1_CC_IRQHandler
	.thumb_set TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM3_IRQHandler
	.thumb_set TIM3_IRQHandler,Default_Handler

	.weak	TIM4_IRQHandler
	.thumb_set TIM4_IRQHandler,Default_Handler

	.weak	TIM5_IRQHandler
	.thumb_set TIM5_IRQHandler,Default_Handler

	.weak	TIM6_IRQHandler
	.thumb_set TIM6_IRQHandler,Default_Handler

	.weak	TIM7_IRQHandler
	.thumb_set TIM7_IRQHandler,Default_Handler

	.weak	TIM9_IRQHandler
	.thumb_set TIM9_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2_IRQHandler
	.thumb_set SPI2_IRQHandler,Default_Handler

	.weak	SPI3_IRQHandler
	.thumb_set SPI3_IRQHandler,Default_Handler

	.weak	SPI4_IRQHandler
	.thumb_set SPI4_IRQHandler,Default_Handler

	.weak	SPI5_IRQHandler
	.thumb_set SPI5_IRQHandler,Default_Handler

	.weak	SPI6_IRQHandler
	.thumb_set SPI6_IRQHandler,Default_Handler

	.weak	HPDMA1_CH0_IRQHandler
	.thumb_set HPDMA1_CH0_IRQHandler,Default_Handler

	.weak	HPDMA1_CH1_IRQHandler
	.thumb_set HPDMA1_CH1_IRQHandler,Default_Handler

	.weak	HPDMA1_CH2_IRQHandler
	.thumb_set HPDMA1_CH2_IRQHandler,Default_Handler

	.weak	HPDMA1_CH3_IRQHandler
	.thumb_set HPDMA1_CH3_IRQHandler,Default_Handler

	.weak	HPDMA1_CH4_IRQHandler
	.thumb_set HPDMA1_CH4_IRQHandler,Default_Handler

	.weak	HPDMA1_CH5_IRQHandler
	.thumb_set HPDMA1_CH5_IRQHandler,Default_Handler

	.weak	HPDMA1_CH6_IRQHandler
	.thumb_set HPDMA1_CH6_IRQHandler,Default_Handler

	.weak	HPDMA1_CH7_IRQHandler
	.thumb_set HPDMA1_CH7_IRQHandler,Default_Handler

	.weak	SAI1_A_IRQHandler
	.thumb_set SAI1_A_IRQHandler,Default_Handler

	.weak	SAI1_B_IRQHandler
	.thumb_set SAI1_B_IRQHandler,Default_Handler

	.weak	SAI2_A_IRQHandler
	.thumb_set SAI2_A_IRQHandler,Default_Handler

	.weak	SAI2_B_IRQHandler
	.thumb_set SAI2_B_IRQHandler,Default_Handler

	.weak	I2C1_EV_IRQHandler
	.thumb_set I2C1_EV_IRQHandler,Default_Handler

	.weak	I2C1_ER_IRQHandler
	.thumb_set I2C1_ER_IRQHandler,Default_Handler

	.weak	I2C2_EV_IRQHandler
	.thumb_set I2C2_EV_IRQHandler,Default_Handler

	.weak	I2C2_ER_IRQHandler
	.thumb_set I2C2_ER_IRQHandler,Default_Handler

	.weak	I2C3_EV_IRQHandler
	.thumb_set I2C3_EV_IRQHandler,Default_Handler

	.weak	I2C3_ER_IRQHandler
	.thumb_set I2C3_ER_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART2_IRQHandler
	.thumb_set USART2_IRQHandler,Default_Handler

	.weak	USART3_IRQHandler
	.thumb_set USART3_IRQHandler,Default_Handler

	.weak	UART4_IRQHandler
	.thumb_set UART4_IRQHandler,Default_Handler

	.weak	UART5_IRQHandler
	.thumb_set UART5_IRQHandler,Default_Handler

	.weak	UART7_IRQHandler
	.thumb_set UART7_IRQHandler,Default_Handler

	.weak	UART8_IRQHandler
	.thumb_set UART8_IRQHandler,Default_Handler

	.weak	I3C1_EV_IRQHandler
	.thumb_set I3C1_EV_IRQHandler,Default_Handler

	.weak	I3C1_ER_IRQHandler
	.thumb_set I3C1_ER_IRQHandler,Default_Handler

	.weak	OTG_HS_IRQHandler
	.thumb_set OTG_HS_IRQHandler,Default_Handler

	.weak	ETH_IRQHandler
	.thumb_set ETH_IRQHandler,Default_Handler

	.weak	CORDIC_IRQHandler
	.thumb_set CORDIC_IRQHandler,Default_Handler

	.weak	GFXTIM_IRQHandler
	.thumb_set GFXTIM_IRQHandler,Default_Handler

	.weak	DCMIPP_IRQHandler
	.thumb_set DCMIPP_IRQHandler,Default_Handler

	.weak	LTDC_IRQHandler
	.thumb_set LTDC_IRQHandler,Default_Handler

	.weak	LTDC_ER_IRQHandler
	.thumb_set LTDC_ER_IRQHandler,Default_Handler

	.weak	DMA2D_IRQHandler
	.thumb_set DMA2D_IRQHandler,Default_Handler

	.weak	JPEG_IRQHandler
	.thumb_set JPEG_IRQHandler,Default_Handler

	.weak	GFXMMU_IRQHandler
	.thumb_set GFXMMU_IRQHandler,Default_Handler

	.weak	I3C1_WKUP_IRQHandler
	.thumb_set I3C1_WKUP_IRQHandler,Default_Handler

	.weak	MCE1_IRQHandler
	.thumb_set MCE1_IRQHandler,Default_Handler

	.weak	MCE2_IRQHandler
	.thumb_set MCE2_IRQHandler,Default_Handler

	.weak	MCE3_IRQHandler
	.thumb_set MCE3_IRQHandler,Default_Handler

	.weak	OSPI1_IRQHandler
	.thumb_set OSPI1_IRQHandler,Default_Handler

	.weak	OSPI2_IRQHandler
	.thumb_set OSPI2_IRQHandler,Default_Handler

	.weak	FMC_IRQHandler
	.thumb_set FMC_IRQHandler,Default_Handler

	.weak	SDMMC1_IRQHandler
	.thumb_set SDMMC1_IRQHandler,Default_Handler

	.weak	SDMMC2_IRQHandler
	.thumb_set SDMMC2_IRQHandler,Default_Handler

	.weak	OTG_FS_IRQHandler
	.thumb_set OTG_FS_IRQHandler,Default_Handler

	.weak	TIM12_IRQHandler
	.thumb_set TIM12_IRQHandler,Default_Handler

	.weak	TIM13_IRQHandler
	.thumb_set TIM13_IRQHandler,Default_Handler

	.weak	TIM14_IRQHandler
	.thumb_set TIM14_IRQHandler,Default_Handler

	.weak	TIM15_IRQHandler
	.thumb_set TIM15_IRQHandler,Default_Handler

	.weak	TIM16_IRQHandler
	.thumb_set TIM16_IRQHandler,Default_Handler

	.weak	TIM17_IRQHandler
	.thumb_set TIM17_IRQHandler,Default_Handler

	.weak	LPTIM1_IRQHandler
	.thumb_set LPTIM1_IRQHandler,Default_Handler

	.weak	LPTIM2_IRQHandler
	.thumb_set LPTIM2_IRQHandler,Default_Handler

	.weak	LPTIM3_IRQHandler
	.thumb_set LPTIM3_IRQHandler,Default_Handler

	.weak	LPTIM4_IRQHandler
	.thumb_set LPTIM4_IRQHandler,Default_Handler

	.weak	LPTIM5_IRQHandler
	.thumb_set LPTIM5_IRQHandler,Default_Handler

	.weak	SPDIF_RX_IRQHandler
	.thumb_set SPDIF_RX_IRQHandler,Default_Handler

	.weak	MDIOS_IRQHandler
	.thumb_set MDIOS_IRQHandler,Default_Handler

	.weak	ADF1_FLT0_IRQHandler
	.thumb_set ADF1_FLT0_IRQHandler,Default_Handler

	.weak	CRS_IRQHandler
	.thumb_set CRS_IRQHandler,Default_Handler

	.weak	UCPD1_IRQHandler
	.thumb_set UCPD1_IRQHandler,Default_Handler

	.weak	CEC_IRQHandler
	.thumb_set CEC_IRQHandler,Default_Handler

	.weak	PSSI_IRQHandler
	.thumb_set PSSI_IRQHandler,Default_Handler

	.weak	LPUART1_IRQHandler
	.thumb_set LPUART1_IRQHandler,Default_Handler

	.weak	WAKEUP_PIN_IRQHandler
	.thumb_set WAKEUP_PIN_IRQHandler,Default_Handler

	.weak	GPDMA1_CH8_IRQHandler
	.thumb_set GPDMA1_CH8_IRQHandler,Default_Handler

	.weak	GPDMA1_CH9_IRQHandler
	.thumb_set GPDMA1_CH9_IRQHandler,Default_Handler

	.weak	GPDMA1_CH10_IRQHandler
	.thumb_set GPDMA1_CH10_IRQHandler,Default_Handler

	.weak	GPDMA1_CH11_IRQHandler
	.thumb_set GPDMA1_CH11_IRQHandler,Default_Handler

	.weak	GPDMA1_CH12_IRQHandler
	.thumb_set GPDMA1_CH12_IRQHandler,Default_Handler

	.weak	GPDMA1_CH13_IRQHandler
	.thumb_set GPDMA1_CH13_IRQHandler,Default_Handler

	.weak	GPDMA1_CH14_IRQHandler
	.thumb_set GPDMA1_CH14_IRQHandler,Default_Handler

	.weak	GPDMA1_CH15_IRQHandler
	.thumb_set GPDMA1_CH15_IRQHandler,Default_Handler

	.weak	HPDMA1_CH8_IRQHandler
	.thumb_set HPDMA1_CH8_IRQHandler,Default_Handler

	.weak	HPDMA1_CH9_IRQHandler
	.thumb_set HPDMA1_CH9_IRQHandler,Default_Handler

	.weak	HPDMA1_CH10_IRQHandler
	.thumb_set HPDMA1_CH10_IRQHandler,Default_Handler

	.weak	HPDMA1_CH11_IRQHandler
	.thumb_set HPDMA1_CH11_IRQHandler,Default_Handler

	.weak	HPDMA1_CH12_IRQHandler
	.thumb_set HPDMA1_CH12_IRQHandler,Default_Handler

	.weak	HPDMA1_CH13_IRQHandler
	.thumb_set HPDMA1_CH13_IRQHandler,Default_Handler

	.weak	HPDMA1_CH14_IRQHandler
	.thumb_set HPDMA1_CH14_IRQHandler,Default_Handler

	.weak	HPDMA1_CH15_IRQHandler
	.thumb_set HPDMA1_CH15_IRQHandler,Default_Handler

	.weak	GPU2D_IRQHandler
	.thumb_set GPU2D_IRQHandler,Default_Handler

	.weak	GPU2D_ER_IRQHandler
	.thumb_set GPU2D_ER_IRQHandler,Default_Handler

	.weak	TCACHE_IRQHandler
	.thumb_set TCACHE_IRQHandler,Default_Handler

	.weak	FDCAN1_IT0_IRQHandler
	.thumb_set FDCAN1_IT0_IRQHandler,Default_Handler

	.weak	FDCAN1_IT1_IRQHandler
	.thumb_set FDCAN1_IT1_IRQHandler,Default_Handler

	.weak	FDCAN2_IT0_IRQHandler
	.thumb_set FDCAN2_IT0_IRQHandler,Default_Handler

	.weak	FDCAN2_IT1_IRQHandler
	.thumb_set FDCAN2_IT1_IRQHandler,Default_Handler

	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
